// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import mock "github.com/stretchr/testify/mock"

// MockTaskExecutor is an autogenerated mock type for the TaskExecutor type
type MockTaskExecutor struct {
	mock.Mock
}

type MockTaskExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskExecutor) EXPECT() *MockTaskExecutor_Expecter {
	return &MockTaskExecutor_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *MockTaskExecutor) Run() {
	_m.Called()
}

// MockTaskExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTaskExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockTaskExecutor_Expecter) Run() *MockTaskExecutor_Run_Call {
	return &MockTaskExecutor_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockTaskExecutor_Run_Call) Run(run func()) *MockTaskExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskExecutor_Run_Call) Return() *MockTaskExecutor_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskExecutor_Run_Call) RunAndReturn(run func()) *MockTaskExecutor_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockTaskExecutor) Stop() {
	_m.Called()
}

// MockTaskExecutor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTaskExecutor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTaskExecutor_Expecter) Stop() *MockTaskExecutor_Stop_Call {
	return &MockTaskExecutor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTaskExecutor_Stop_Call) Run(run func()) *MockTaskExecutor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskExecutor_Stop_Call) Return() *MockTaskExecutor_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskExecutor_Stop_Call) RunAndReturn(run func()) *MockTaskExecutor_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockTaskExecutor creates a new instance of MockTaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskExecutor {
	mock := &MockTaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
