// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import mock "github.com/stretchr/testify/mock"

// MockTaskRunner is an autogenerated mock type for the TaskRunner type
type MockTaskRunner struct {
	mock.Mock
}

type MockTaskRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRunner) EXPECT() *MockTaskRunner_Expecter {
	return &MockTaskRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *MockTaskRunner) Run() {
	_m.Called()
}

// MockTaskRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTaskRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockTaskRunner_Expecter) Run() *MockTaskRunner_Run_Call {
	return &MockTaskRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockTaskRunner_Run_Call) Run(run func()) *MockTaskRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskRunner_Run_Call) Return() *MockTaskRunner_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskRunner_Run_Call) RunAndReturn(run func()) *MockTaskRunner_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockTaskRunner) Stop() {
	_m.Called()
}

// MockTaskRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTaskRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTaskRunner_Expecter) Stop() *MockTaskRunner_Stop_Call {
	return &MockTaskRunner_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTaskRunner_Stop_Call) Run(run func()) *MockTaskRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskRunner_Stop_Call) Return() *MockTaskRunner_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskRunner_Stop_Call) RunAndReturn(run func()) *MockTaskRunner_Stop_Call {
	_c.Run(run)
	return _c
}

// Stopped provides a mock function with no fields
func (_m *MockTaskRunner) Stopped() chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stopped")
	}

	var r0 chan struct{}
	if rf, ok := ret.Get(0).(func() chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan struct{})
		}
	}

	return r0
}

// MockTaskRunner_Stopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stopped'
type MockTaskRunner_Stopped_Call struct {
	*mock.Call
}

// Stopped is a helper method to define mock.On call
func (_e *MockTaskRunner_Expecter) Stopped() *MockTaskRunner_Stopped_Call {
	return &MockTaskRunner_Stopped_Call{Call: _e.mock.On("Stopped")}
}

func (_c *MockTaskRunner_Stopped_Call) Run(run func()) *MockTaskRunner_Stopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskRunner_Stopped_Call) Return(_a0 chan struct{}) *MockTaskRunner_Stopped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRunner_Stopped_Call) RunAndReturn(run func() chan struct{}) *MockTaskRunner_Stopped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRunner creates a new instance of MockTaskRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRunner {
	mock := &MockTaskRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
