// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockJobFunc is an autogenerated mock type for the JobFunc type
type MockJobFunc struct {
	mock.Mock
}

type MockJobFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobFunc) EXPECT() *MockJobFunc_Expecter {
	return &MockJobFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockJobFunc) Execute(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockJobFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobFunc_Expecter) Execute(ctx interface{}) *MockJobFunc_Execute_Call {
	return &MockJobFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockJobFunc_Execute_Call) Run(run func(ctx context.Context)) *MockJobFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockJobFunc_Execute_Call) Return(_a0 int, _a1 error) *MockJobFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobFunc_Execute_Call) RunAndReturn(run func(context.Context) (int, error)) *MockJobFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobFunc creates a new instance of MockJobFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobFunc {
	mock := &MockJobFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
