// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import mock "github.com/stretchr/testify/mock"

// mockTaskRunner is an autogenerated mock type for the taskRunner type
type mockTaskRunner struct {
	mock.Mock
}

type mockTaskRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTaskRunner) EXPECT() *mockTaskRunner_Expecter {
	return &mockTaskRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *mockTaskRunner) Run() {
	_m.Called()
}

// mockTaskRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockTaskRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *mockTaskRunner_Expecter) Run() *mockTaskRunner_Run_Call {
	return &mockTaskRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *mockTaskRunner_Run_Call) Run(run func()) *mockTaskRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTaskRunner_Run_Call) Return() *mockTaskRunner_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTaskRunner_Run_Call) RunAndReturn(run func()) *mockTaskRunner_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *mockTaskRunner) Stop() {
	_m.Called()
}

// mockTaskRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockTaskRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *mockTaskRunner_Expecter) Stop() *mockTaskRunner_Stop_Call {
	return &mockTaskRunner_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *mockTaskRunner_Stop_Call) Run(run func()) *mockTaskRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTaskRunner_Stop_Call) Return() *mockTaskRunner_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTaskRunner_Stop_Call) RunAndReturn(run func()) *mockTaskRunner_Stop_Call {
	_c.Run(run)
	return _c
}

// newMockTaskRunner creates a new instance of mockTaskRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskRunner {
	mock := &mockTaskRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
