// Code generated by mockery v2.53.3. DO NOT EDIT.

package producer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceAccountClient is an autogenerated mock type for the ServiceAccountClient type
type MockServiceAccountClient struct {
	mock.Mock
}

type MockServiceAccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceAccountClient) EXPECT() *MockServiceAccountClient_Expecter {
	return &MockServiceAccountClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, consumer, params
func (_m *MockServiceAccountClient) Create(ctx context.Context, consumer string, params Params) (map[string]string, error) {
	ret := _m.Called(ctx, consumer, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, Params) (map[string]string, error)); ok {
		return rf(ctx, consumer, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, Params) map[string]string); ok {
		r0 = rf(ctx, consumer, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, Params) error); ok {
		r1 = rf(ctx, consumer, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceAccountClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceAccountClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - params Params
func (_e *MockServiceAccountClient_Expecter) Create(ctx interface{}, consumer interface{}, params interface{}) *MockServiceAccountClient_Create_Call {
	return &MockServiceAccountClient_Create_Call{Call: _e.mock.On("Create", ctx, consumer, params)}
}

func (_c *MockServiceAccountClient_Create_Call) Run(run func(ctx context.Context, consumer string, params Params)) *MockServiceAccountClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(Params))
	})
	return _c
}

func (_c *MockServiceAccountClient_Create_Call) Return(_a0 map[string]string, _a1 error) *MockServiceAccountClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceAccountClient_Create_Call) RunAndReturn(run func(context.Context, string, Params) (map[string]string, error)) *MockServiceAccountClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, consumer
func (_m *MockServiceAccountClient) Delete(ctx context.Context, consumer string) error {
	ret := _m.Called(ctx, consumer)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceAccountClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceAccountClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
func (_e *MockServiceAccountClient_Expecter) Delete(ctx interface{}, consumer interface{}) *MockServiceAccountClient_Delete_Call {
	return &MockServiceAccountClient_Delete_Call{Call: _e.mock.On("Delete", ctx, consumer)}
}

func (_c *MockServiceAccountClient_Delete_Call) Run(run func(ctx context.Context, consumer string)) *MockServiceAccountClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServiceAccountClient_Delete_Call) Return(_a0 error) *MockServiceAccountClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAccountClient_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockServiceAccountClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, consumer, params
func (_m *MockServiceAccountClient) Update(ctx context.Context, consumer string, params Params) (map[string]string, error) {
	ret := _m.Called(ctx, consumer, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, Params) (map[string]string, error)); ok {
		return rf(ctx, consumer, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, Params) map[string]string); ok {
		r0 = rf(ctx, consumer, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, Params) error); ok {
		r1 = rf(ctx, consumer, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceAccountClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceAccountClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - params Params
func (_e *MockServiceAccountClient_Expecter) Update(ctx interface{}, consumer interface{}, params interface{}) *MockServiceAccountClient_Update_Call {
	return &MockServiceAccountClient_Update_Call{Call: _e.mock.On("Update", ctx, consumer, params)}
}

func (_c *MockServiceAccountClient_Update_Call) Run(run func(ctx context.Context, consumer string, params Params)) *MockServiceAccountClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(Params))
	})
	return _c
}

func (_c *MockServiceAccountClient_Update_Call) Return(_a0 map[string]string, _a1 error) *MockServiceAccountClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceAccountClient_Update_Call) RunAndReturn(run func(context.Context, string, Params) (map[string]string, error)) *MockServiceAccountClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceAccountClient creates a new instance of MockServiceAccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceAccountClient {
	mock := &MockServiceAccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
