// Code generated by mockery v2.53.3. DO NOT EDIT.

package producer

import (
	context "context"

	v2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	internalproducer "github.com/cloudogu/service-account-operator/internal/producer"
	mock "github.com/stretchr/testify/mock"
)

// mockClientFactory is an autogenerated mock type for the clientFactory type
type mockClientFactory struct {
	mock.Mock
}

type mockClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClientFactory) EXPECT() *mockClientFactory_Expecter {
	return &mockClientFactory_Expecter{mock: &_m.Mock}
}

// NewForProducer provides a mock function with given fields: ctx, namespace, sapr
func (_m *mockClientFactory) NewForProducer(ctx context.Context, namespace string, sapr *v2.ServiceAccountProducer) (internalproducer.ServiceAccountClient, error) {
	ret := _m.Called(ctx, namespace, sapr)

	if len(ret) == 0 {
		panic("no return value specified for NewForProducer")
	}

	var r0 internalproducer.ServiceAccountClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v2.ServiceAccountProducer) (internalproducer.ServiceAccountClient, error)); ok {
		return rf(ctx, namespace, sapr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v2.ServiceAccountProducer) internalproducer.ServiceAccountClient); ok {
		r0 = rf(ctx, namespace, sapr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internalproducer.ServiceAccountClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v2.ServiceAccountProducer) error); ok {
		r1 = rf(ctx, namespace, sapr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockClientFactory_NewForProducer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewForProducer'
type mockClientFactory_NewForProducer_Call struct {
	*mock.Call
}

// NewForProducer is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sapr *v2.ServiceAccountProducer
func (_e *mockClientFactory_Expecter) NewForProducer(ctx interface{}, namespace interface{}, sapr interface{}) *mockClientFactory_NewForProducer_Call {
	return &mockClientFactory_NewForProducer_Call{Call: _e.mock.On("NewForProducer", ctx, namespace, sapr)}
}

func (_c *mockClientFactory_NewForProducer_Call) Run(run func(ctx context.Context, namespace string, sapr *v2.ServiceAccountProducer)) *mockClientFactory_NewForProducer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v2.ServiceAccountProducer))
	})
	return _c
}

func (_c *mockClientFactory_NewForProducer_Call) Return(_a0 internalproducer.ServiceAccountClient, _a1 error) *mockClientFactory_NewForProducer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockClientFactory_NewForProducer_Call) RunAndReturn(run func(context.Context, string, *v2.ServiceAccountProducer) (internalproducer.ServiceAccountClient, error)) *mockClientFactory_NewForProducer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockClientFactory creates a new instance of mockClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClientFactory {
	mock := &mockClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
