// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// mockStatusClient is an autogenerated mock type for the statusClient type
type mockStatusClient struct {
	mock.Mock
}

type mockStatusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStatusClient) EXPECT() *mockStatusClient_Expecter {
	return &mockStatusClient_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, obj, opts
func (_m *mockStatusClient) Apply(ctx context.Context, obj runtime.ApplyConfiguration, opts ...client.SubResourceApplyOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, runtime.ApplyConfiguration, ...client.SubResourceApplyOption) error); ok {
		r0 = rf(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusClient_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockStatusClient_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - obj runtime.ApplyConfiguration
//   - opts ...client.SubResourceApplyOption
func (_e *mockStatusClient_Expecter) Apply(ctx interface{}, obj interface{}, opts ...interface{}) *mockStatusClient_Apply_Call {
	return &mockStatusClient_Apply_Call{Call: _e.mock.On("Apply",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *mockStatusClient_Apply_Call) Run(run func(ctx context.Context, obj runtime.ApplyConfiguration, opts ...client.SubResourceApplyOption)) *mockStatusClient_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.SubResourceApplyOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.SubResourceApplyOption)
			}
		}
		run(args[0].(context.Context), args[1].(runtime.ApplyConfiguration), variadicArgs...)
	})
	return _c
}

func (_c *mockStatusClient_Apply_Call) Return(_a0 error) *mockStatusClient_Apply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusClient_Apply_Call) RunAndReturn(run func(context.Context, runtime.ApplyConfiguration, ...client.SubResourceApplyOption) error) *mockStatusClient_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, obj, subResource, opts
func (_m *mockStatusClient) Create(ctx context.Context, obj client.Object, subResource client.Object, opts ...client.SubResourceCreateOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj, subResource)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, client.Object, ...client.SubResourceCreateOption) error); ok {
		r0 = rf(ctx, obj, subResource, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockStatusClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - subResource client.Object
//   - opts ...client.SubResourceCreateOption
func (_e *mockStatusClient_Expecter) Create(ctx interface{}, obj interface{}, subResource interface{}, opts ...interface{}) *mockStatusClient_Create_Call {
	return &mockStatusClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, obj, subResource}, opts...)...)}
}

func (_c *mockStatusClient_Create_Call) Run(run func(ctx context.Context, obj client.Object, subResource client.Object, opts ...client.SubResourceCreateOption)) *mockStatusClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.SubResourceCreateOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.SubResourceCreateOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.Object), args[2].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *mockStatusClient_Create_Call) Return(_a0 error) *mockStatusClient_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusClient_Create_Call) RunAndReturn(run func(context.Context, client.Object, client.Object, ...client.SubResourceCreateOption) error) *mockStatusClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, obj, patch, opts
func (_m *mockStatusClient) Patch(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj, patch)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, client.Patch, ...client.SubResourcePatchOption) error); ok {
		r0 = rf(ctx, obj, patch, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockStatusClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - patch client.Patch
//   - opts ...client.SubResourcePatchOption
func (_e *mockStatusClient_Expecter) Patch(ctx interface{}, obj interface{}, patch interface{}, opts ...interface{}) *mockStatusClient_Patch_Call {
	return &mockStatusClient_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, obj, patch}, opts...)...)}
}

func (_c *mockStatusClient_Patch_Call) Run(run func(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption)) *mockStatusClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.SubResourcePatchOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.SubResourcePatchOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.Object), args[2].(client.Patch), variadicArgs...)
	})
	return _c
}

func (_c *mockStatusClient_Patch_Call) Return(_a0 error) *mockStatusClient_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusClient_Patch_Call) RunAndReturn(run func(context.Context, client.Object, client.Patch, ...client.SubResourcePatchOption) error) *mockStatusClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, obj, opts
func (_m *mockStatusClient) Update(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, ...client.SubResourceUpdateOption) error); ok {
		r0 = rf(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockStatusClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - opts ...client.SubResourceUpdateOption
func (_e *mockStatusClient_Expecter) Update(ctx interface{}, obj interface{}, opts ...interface{}) *mockStatusClient_Update_Call {
	return &mockStatusClient_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *mockStatusClient_Update_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption)) *mockStatusClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.SubResourceUpdateOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.SubResourceUpdateOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *mockStatusClient_Update_Call) Return(_a0 error) *mockStatusClient_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusClient_Update_Call) RunAndReturn(run func(context.Context, client.Object, ...client.SubResourceUpdateOption) error) *mockStatusClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStatusClient creates a new instance of mockStatusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStatusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStatusClient {
	mock := &mockStatusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
