// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	producer "github.com/cloudogu/service-account-operator/internal/producer"
	mock "github.com/stretchr/testify/mock"
)

// mockHttpClientFactory is an autogenerated mock type for the httpClientFactory type
type mockHttpClientFactory struct {
	mock.Mock
}

type mockHttpClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHttpClientFactory) EXPECT() *mockHttpClientFactory_Expecter {
	return &mockHttpClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: endpoint, apiKey
func (_m *mockHttpClientFactory) New(endpoint string, apiKey string) producer.HTTPClient {
	ret := _m.Called(endpoint, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 producer.HTTPClient
	if rf, ok := ret.Get(0).(func(string, string) producer.HTTPClient); ok {
		r0 = rf(endpoint, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(producer.HTTPClient)
		}
	}

	return r0
}

// mockHttpClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type mockHttpClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - endpoint string
//   - apiKey string
func (_e *mockHttpClientFactory_Expecter) New(endpoint interface{}, apiKey interface{}) *mockHttpClientFactory_New_Call {
	return &mockHttpClientFactory_New_Call{Call: _e.mock.On("New", endpoint, apiKey)}
}

func (_c *mockHttpClientFactory_New_Call) Run(run func(endpoint string, apiKey string)) *mockHttpClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockHttpClientFactory_New_Call) Return(_a0 producer.HTTPClient) *mockHttpClientFactory_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHttpClientFactory_New_Call) RunAndReturn(run func(string, string) producer.HTTPClient) *mockHttpClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHttpClientFactory creates a new instance of mockHttpClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHttpClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHttpClientFactory {
	mock := &mockHttpClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
