// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	context "context"

	producer "github.com/cloudogu/service-account-operator/internal/producer"
	mock "github.com/stretchr/testify/mock"
)

// mockServiceAccountClient is an autogenerated mock type for the serviceAccountClient type
type mockServiceAccountClient struct {
	mock.Mock
}

type mockServiceAccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceAccountClient) EXPECT() *mockServiceAccountClient_Expecter {
	return &mockServiceAccountClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, consumer, params
func (_m *mockServiceAccountClient) Create(ctx context.Context, consumer string, params producer.Params) (map[string]string, error) {
	ret := _m.Called(ctx, consumer, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, producer.Params) (map[string]string, error)); ok {
		return rf(ctx, consumer, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, producer.Params) map[string]string); ok {
		r0 = rf(ctx, consumer, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, producer.Params) error); ok {
		r1 = rf(ctx, consumer, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceAccountClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockServiceAccountClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - params producer.Params
func (_e *mockServiceAccountClient_Expecter) Create(ctx interface{}, consumer interface{}, params interface{}) *mockServiceAccountClient_Create_Call {
	return &mockServiceAccountClient_Create_Call{Call: _e.mock.On("Create", ctx, consumer, params)}
}

func (_c *mockServiceAccountClient_Create_Call) Run(run func(ctx context.Context, consumer string, params producer.Params)) *mockServiceAccountClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(producer.Params))
	})
	return _c
}

func (_c *mockServiceAccountClient_Create_Call) Return(_a0 map[string]string, _a1 error) *mockServiceAccountClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceAccountClient_Create_Call) RunAndReturn(run func(context.Context, string, producer.Params) (map[string]string, error)) *mockServiceAccountClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, consumer
func (_m *mockServiceAccountClient) Delete(ctx context.Context, consumer string) error {
	ret := _m.Called(ctx, consumer)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockServiceAccountClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockServiceAccountClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
func (_e *mockServiceAccountClient_Expecter) Delete(ctx interface{}, consumer interface{}) *mockServiceAccountClient_Delete_Call {
	return &mockServiceAccountClient_Delete_Call{Call: _e.mock.On("Delete", ctx, consumer)}
}

func (_c *mockServiceAccountClient_Delete_Call) Run(run func(ctx context.Context, consumer string)) *mockServiceAccountClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockServiceAccountClient_Delete_Call) Return(_a0 error) *mockServiceAccountClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockServiceAccountClient_Delete_Call) RunAndReturn(run func(context.Context, string) error) *mockServiceAccountClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, consumer
func (_m *mockServiceAccountClient) Exists(ctx context.Context, consumer string) (bool, error) {
	ret := _m.Called(ctx, consumer)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, consumer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, consumer)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, consumer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceAccountClient_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockServiceAccountClient_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
func (_e *mockServiceAccountClient_Expecter) Exists(ctx interface{}, consumer interface{}) *mockServiceAccountClient_Exists_Call {
	return &mockServiceAccountClient_Exists_Call{Call: _e.mock.On("Exists", ctx, consumer)}
}

func (_c *mockServiceAccountClient_Exists_Call) Run(run func(ctx context.Context, consumer string)) *mockServiceAccountClient_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockServiceAccountClient_Exists_Call) Return(_a0 bool, _a1 error) *mockServiceAccountClient_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceAccountClient_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *mockServiceAccountClient_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with given fields: ctx
func (_m *mockServiceAccountClient) Ready(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockServiceAccountClient_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type mockServiceAccountClient_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockServiceAccountClient_Expecter) Ready(ctx interface{}) *mockServiceAccountClient_Ready_Call {
	return &mockServiceAccountClient_Ready_Call{Call: _e.mock.On("Ready", ctx)}
}

func (_c *mockServiceAccountClient_Ready_Call) Run(run func(ctx context.Context)) *mockServiceAccountClient_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockServiceAccountClient_Ready_Call) Return(_a0 error) *mockServiceAccountClient_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockServiceAccountClient_Ready_Call) RunAndReturn(run func(context.Context) error) *mockServiceAccountClient_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, consumer, params
func (_m *mockServiceAccountClient) Update(ctx context.Context, consumer string, params producer.Params) (map[string]string, error) {
	ret := _m.Called(ctx, consumer, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, producer.Params) (map[string]string, error)); ok {
		return rf(ctx, consumer, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, producer.Params) map[string]string); ok {
		r0 = rf(ctx, consumer, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, producer.Params) error); ok {
		r1 = rf(ctx, consumer, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceAccountClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockServiceAccountClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - params producer.Params
func (_e *mockServiceAccountClient_Expecter) Update(ctx interface{}, consumer interface{}, params interface{}) *mockServiceAccountClient_Update_Call {
	return &mockServiceAccountClient_Update_Call{Call: _e.mock.On("Update", ctx, consumer, params)}
}

func (_c *mockServiceAccountClient_Update_Call) Run(run func(ctx context.Context, consumer string, params producer.Params)) *mockServiceAccountClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(producer.Params))
	})
	return _c
}

func (_c *mockServiceAccountClient_Update_Call) Return(_a0 map[string]string, _a1 error) *mockServiceAccountClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceAccountClient_Update_Call) RunAndReturn(run func(context.Context, string, producer.Params) (map[string]string, error)) *mockServiceAccountClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceAccountClient creates a new instance of mockServiceAccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceAccountClient {
	mock := &mockServiceAccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
