// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	context "context"

	cron "github.com/cloudogu/service-account-operator/internal/controller/request/cron"
	mock "github.com/stretchr/testify/mock"
)

// mockTaskRunnerFactory is an autogenerated mock type for the taskRunnerFactory type
type mockTaskRunnerFactory struct {
	mock.Mock
}

type mockTaskRunnerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTaskRunnerFactory) EXPECT() *mockTaskRunnerFactory_Expecter {
	return &mockTaskRunnerFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: ctx, expr, jobClosure
func (_m *mockTaskRunnerFactory) New(ctx context.Context, expr string, jobClosure cron.JobFunc) (cron.TaskRunner, error) {
	ret := _m.Called(ctx, expr, jobClosure)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 cron.TaskRunner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, cron.JobFunc) (cron.TaskRunner, error)); ok {
		return rf(ctx, expr, jobClosure)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, cron.JobFunc) cron.TaskRunner); ok {
		r0 = rf(ctx, expr, jobClosure)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cron.TaskRunner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, cron.JobFunc) error); ok {
		r1 = rf(ctx, expr, jobClosure)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockTaskRunnerFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type mockTaskRunnerFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
//   - expr string
//   - jobClosure cron.JobFunc
func (_e *mockTaskRunnerFactory_Expecter) New(ctx interface{}, expr interface{}, jobClosure interface{}) *mockTaskRunnerFactory_New_Call {
	return &mockTaskRunnerFactory_New_Call{Call: _e.mock.On("New", ctx, expr, jobClosure)}
}

func (_c *mockTaskRunnerFactory_New_Call) Run(run func(ctx context.Context, expr string, jobClosure cron.JobFunc)) *mockTaskRunnerFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(cron.JobFunc))
	})
	return _c
}

func (_c *mockTaskRunnerFactory_New_Call) Return(_a0 cron.TaskRunner, _a1 error) *mockTaskRunnerFactory_New_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockTaskRunnerFactory_New_Call) RunAndReturn(run func(context.Context, string, cron.JobFunc) (cron.TaskRunner, error)) *mockTaskRunnerFactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTaskRunnerFactory creates a new instance of mockTaskRunnerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskRunnerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskRunnerFactory {
	mock := &mockTaskRunnerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
