// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	context "context"

	v1 "github.com/cloudogu/k8s-serviceaccount-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockSecretManager is an autogenerated mock type for the secretManager type
type mockSecretManager struct {
	mock.Mock
}

type mockSecretManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSecretManager) EXPECT() *mockSecretManager_Expecter {
	return &mockSecretManager_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function with given fields: ctx, sare, credentials
func (_m *mockSecretManager) CreateOrUpdate(ctx context.Context, sare *v1.ServiceAccountRequest, credentials map[string]string) (string, error) {
	ret := _m.Called(ctx, sare, credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ServiceAccountRequest, map[string]string) (string, error)); ok {
		return rf(ctx, sare, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ServiceAccountRequest, map[string]string) string); ok {
		r0 = rf(ctx, sare, credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ServiceAccountRequest, map[string]string) error); ok {
		r1 = rf(ctx, sare, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretManager_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type mockSecretManager_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - sare *v1.ServiceAccountRequest
//   - credentials map[string]string
func (_e *mockSecretManager_Expecter) CreateOrUpdate(ctx interface{}, sare interface{}, credentials interface{}) *mockSecretManager_CreateOrUpdate_Call {
	return &mockSecretManager_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, sare, credentials)}
}

func (_c *mockSecretManager_CreateOrUpdate_Call) Run(run func(ctx context.Context, sare *v1.ServiceAccountRequest, credentials map[string]string)) *mockSecretManager_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ServiceAccountRequest), args[2].(map[string]string))
	})
	return _c
}

func (_c *mockSecretManager_CreateOrUpdate_Call) Return(_a0 string, _a1 error) *mockSecretManager_CreateOrUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretManager_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, *v1.ServiceAccountRequest, map[string]string) (string, error)) *mockSecretManager_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, sare
func (_m *mockSecretManager) Exists(ctx context.Context, sare *v1.ServiceAccountRequest) (bool, error) {
	ret := _m.Called(ctx, sare)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ServiceAccountRequest) (bool, error)); ok {
		return rf(ctx, sare)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ServiceAccountRequest) bool); ok {
		r0 = rf(ctx, sare)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ServiceAccountRequest) error); ok {
		r1 = rf(ctx, sare)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretManager_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockSecretManager_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - sare *v1.ServiceAccountRequest
func (_e *mockSecretManager_Expecter) Exists(ctx interface{}, sare interface{}) *mockSecretManager_Exists_Call {
	return &mockSecretManager_Exists_Call{Call: _e.mock.On("Exists", ctx, sare)}
}

func (_c *mockSecretManager_Exists_Call) Run(run func(ctx context.Context, sare *v1.ServiceAccountRequest)) *mockSecretManager_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ServiceAccountRequest))
	})
	return _c
}

func (_c *mockSecretManager_Exists_Call) Return(_a0 bool, _a1 error) *mockSecretManager_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretManager_Exists_Call) RunAndReturn(run func(context.Context, *v1.ServiceAccountRequest) (bool, error)) *mockSecretManager_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSecretManager creates a new instance of mockSecretManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSecretManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSecretManager {
	mock := &mockSecretManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
