// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// mockEventRecorder is an autogenerated mock type for the eventRecorder type
type mockEventRecorder struct {
	mock.Mock
}

type mockEventRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEventRecorder) EXPECT() *mockEventRecorder_Expecter {
	return &mockEventRecorder_Expecter{mock: &_m.Mock}
}

// Eventf provides a mock function with given fields: regarding, related, eventtype, reason, action, note, args
func (_m *mockEventRecorder) Eventf(regarding runtime.Object, related runtime.Object, eventtype string, reason string, action string, note string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, regarding, related, eventtype, reason, action, note)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockEventRecorder_Eventf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eventf'
type mockEventRecorder_Eventf_Call struct {
	*mock.Call
}

// Eventf is a helper method to define mock.On call
//   - regarding runtime.Object
//   - related runtime.Object
//   - eventtype string
//   - reason string
//   - action string
//   - note string
//   - args ...interface{}
func (_e *mockEventRecorder_Expecter) Eventf(regarding interface{}, related interface{}, eventtype interface{}, reason interface{}, action interface{}, note interface{}, args ...interface{}) *mockEventRecorder_Eventf_Call {
	return &mockEventRecorder_Eventf_Call{Call: _e.mock.On("Eventf",
		append([]interface{}{regarding, related, eventtype, reason, action, note}, args...)...)}
}

func (_c *mockEventRecorder_Eventf_Call) Run(run func(regarding runtime.Object, related runtime.Object, eventtype string, reason string, action string, note string, args ...interface{})) *mockEventRecorder_Eventf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-6)
		for i, a := range args[6:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(runtime.Object), args[1].(runtime.Object), args[2].(string), args[3].(string), args[4].(string), args[5].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockEventRecorder_Eventf_Call) Return() *mockEventRecorder_Eventf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockEventRecorder_Eventf_Call) RunAndReturn(run func(runtime.Object, runtime.Object, string, string, string, string, ...interface{})) *mockEventRecorder_Eventf_Call {
	_c.Run(run)
	return _c
}

// newMockEventRecorder creates a new instance of mockEventRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEventRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEventRecorder {
	mock := &mockEventRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
