// Code generated by mockery v2.53.3. DO NOT EDIT.

package request

import (
	context "context"

	v2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	producer "github.com/cloudogu/service-account-operator/internal/producer"
	mock "github.com/stretchr/testify/mock"
)

// mockProducerClientFactory is an autogenerated mock type for the producerClientFactory type
type mockProducerClientFactory struct {
	mock.Mock
}

type mockProducerClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProducerClientFactory) EXPECT() *mockProducerClientFactory_Expecter {
	return &mockProducerClientFactory_Expecter{mock: &_m.Mock}
}

// NewForProducer provides a mock function with given fields: ctx, namespace, sapr
func (_m *mockProducerClientFactory) NewForProducer(ctx context.Context, namespace string, sapr *v2.ServiceAccountProducer) (producer.ServiceAccountClient, error) {
	ret := _m.Called(ctx, namespace, sapr)

	if len(ret) == 0 {
		panic("no return value specified for NewForProducer")
	}

	var r0 producer.ServiceAccountClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v2.ServiceAccountProducer) (producer.ServiceAccountClient, error)); ok {
		return rf(ctx, namespace, sapr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v2.ServiceAccountProducer) producer.ServiceAccountClient); ok {
		r0 = rf(ctx, namespace, sapr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(producer.ServiceAccountClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v2.ServiceAccountProducer) error); ok {
		r1 = rf(ctx, namespace, sapr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockProducerClientFactory_NewForProducer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewForProducer'
type mockProducerClientFactory_NewForProducer_Call struct {
	*mock.Call
}

// NewForProducer is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - sapr *v2.ServiceAccountProducer
func (_e *mockProducerClientFactory_Expecter) NewForProducer(ctx interface{}, namespace interface{}, sapr interface{}) *mockProducerClientFactory_NewForProducer_Call {
	return &mockProducerClientFactory_NewForProducer_Call{Call: _e.mock.On("NewForProducer", ctx, namespace, sapr)}
}

func (_c *mockProducerClientFactory_NewForProducer_Call) Run(run func(ctx context.Context, namespace string, sapr *v2.ServiceAccountProducer)) *mockProducerClientFactory_NewForProducer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v2.ServiceAccountProducer))
	})
	return _c
}

func (_c *mockProducerClientFactory_NewForProducer_Call) Return(_a0 producer.ServiceAccountClient, _a1 error) *mockProducerClientFactory_NewForProducer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockProducerClientFactory_NewForProducer_Call) RunAndReturn(run func(context.Context, string, *v2.ServiceAccountProducer) (producer.ServiceAccountClient, error)) *mockProducerClientFactory_NewForProducer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProducerClientFactory creates a new instance of mockProducerClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProducerClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProducerClientFactory {
	mock := &mockProducerClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
